#!/usr/bin/sh

curl -L 'https://www.nerdfonts.com/assets/css/webfont.css' --output static/nerdfont.css
sed -i 's#\.\./fonts/Symbols-2048-em Nerd Font Complete.woff2#/static/nerdfont.woff2#' static/nerdfont.css

curl -L 'https://www.nerdfonts.com/assets/fonts/Symbols-2048-em%20Nerd%20Font%20Complete.woff2' --output static/nerdfont.woff2

curl -L 'http://afarkas.github.io/lazysizes/lazysizes.min.js' --output static/lazysizes.min.js
