#!/usr/bin/sh

curl -LO 'https://www.nerdfonts.com/assets/css/webfont.css'
mv webfont.css static/nerdfont.css
sed -i 's#\.\./fonts/Symbols-2048-em Nerd Font Complete.woff2#/static/nerdfont.woff2#' static/nerdfont.css

curl -LO 'https://www.nerdfonts.com/assets/fonts/Symbols-2048-em%20Nerd%20Font%20Complete.woff2'
mv 'Symbols-2048-em%20Nerd%20Font%20Complete.woff2' static/nerdfont.woff2
